spring:
  application:
    name: testDemo
  datasource:
    url: jdbc:sqlite::resource:test.db
    driver-class-name: org.sqlite.JDBC
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:./jssdk
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: net.luculent.trenddbmanage.user.entity

server:
  port: 20000
  address: 127.0.0.1




